name: Issues workflow

on:
  issues:
    types: [opened]
    
jobs:
  respond:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v1
            with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '👋 Thanks for reporting!'
                })
